export {
  RealtimeHub,
  createRealtimeHub,
  decodeMessage,
  CONNECTION_OPEN,
  DEFAULT_LIMITS,
  DEFAULT_HEARTBEAT,
  DEFAULT_BACKPRESSURE,
  type Client,
  type ClientInput,
  type JoinOptions,
  type Connection,
  type BroadcastTarget,
  type BroadcastOptions,
  type Logger,
  type RealtimeLimits,
  type HeartbeatOptions,
  type BackpressureOptions,
  type RealtimeAction,
  type AuthenticateContext,
  type AuthenticateHook,
  type AuthorizeContext,
  type AuthorizeHook,
  type RealtimeEvent,
  type RealtimeEventName,
  type RealtimeHubStats,
  type RealtimeHubOptions,
  type CreateRealtimeHubOptions,
  type E2EEFrame,
  type ClientRef,
} from "./hub.js";

export {
  RealtimeError,
  ConnectionError,
  ConnectionClosedError,
  ChannelError,
  AuthenticationError,
  AuthorizationError,
  MessageTooLargeError,
  ConnectionLimitError,
  type RealtimeErrorCode,
} from "./errors.js";

export {
  createConnectionAdapter,
  attachWebSocketAdapter,
  matchesPath,
  type ConnectionAdapter,
  type ConnectionAdapterOptions,
  type AttachedWebSocketAdapter,
  type AttachWebSocketAdapterOptions,
  type HttpServerLike,
  type WebSocketServerLike,
  type RealtimeConnection,
  type RealtimeConnectionHandler,
  type RealtimeMessageHandler,
} from "./adapter.js";

export {
  registerRealtime,
  realtimePlugin,
  matchesRealtimePath,
  type RealtimePluginOptions,
  type RealtimePluginLogger,
} from "./plugin.js";

export {
  generateKeyPair,
  generateSigningKeyPair,
  encrypt,
  decrypt,
  sign,
  verify,
  computeSharedKey,
  encryptWithSharedKey,
  decryptWithSharedKey,
  toBase64,
  fromBase64,
  keyToHex,
  keyFromHex,
  e2eeReady,
  isE2EEReady,
  type KeyPair,
  type SharedKeyData,
} from "./e2ee.js";